name: TreasureWolf
version: 1.0.0
main: com.yourname.treasurewolf.TreasureWolfPlugin
api-version: 1.19
author: YourName
description: Волки ищут клады с сокровищами

commands:
  treasure:
    description: Основная команда плагина
    usage: /treasure <reload|info|help>
    aliases: [tw, treasurewolf]

permissions:
  treasurewolf.use:
    description: Разрешение на использование основных функций плагина
    default: true
  treasurewolf.reload:
    description: Разрешение на перезагрузку конфигурации
    default: op
  treasurewolf.admin:
    description: Полный доступ к плагину
    default: op
    children:
      treasurewolf.use: true
      treasurewolf.reload: true